apiVersion: v1
kind: Service
metadata:
  name: frontendend-service
  labels: 
    name: frontendend-service
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8080
  selector:
    name: frontendend-pod