apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels: 
    name: backend-service
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    name: backend-pod